### ISSUE TITLE
grammar lex: stanley peters verb learning comment

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#48]
To expand a little on a comment I made during your very interesting presentation yesterday, lexicalist theories of grammar seem to predict that development of syntax is driven more by verbs and adjectives than by nouns (that are not deverbal or deadjectival ones). So it's somewhat surprising on this view that grammar development tracks vocabulary development even at early stages, when more nouns are acquired than verbs or adjectives. Lexicalist theories would seem to predict that grammar development would lag vocabulary development until acquisition of verbs and adjectives begins to catch up with acquisition of nouns.

I don't know whether CDI isn't a sensitive enough instrument to detect this lag, many deverbal nouns are acquired earlier than the verbs from which they morphologically derive, or the apparently close correlation is inconsistent with lexicalist theories. It struck me as a question worth further thought.

**Comment by vmarchman** [comment]
I think his intuition is right and it is exactly what is behind the idea of a "critical mass" of lexical forms.  The developmental trajectory is non-linear, meaning that lexical development is proceeding and the onset of grammar somewhat lags behind lexical development.  Grammar begins to take off once the child has say >200 words, presumably many of those (at that point) are non-nominal forms. Now, Dixon & Marchman (2005) did show that some of that non-linearity was due to measurement properties of the complexity section on the CDI (i.e., the complexity section was not as good at picking up on change earlier in development as it was later in development), but if you take the relation at face value, lexical development and grammatical development are not "tracking" equally across development.

**Comment by vmarchman** [comment]
Related to the other comment that came up regarding how could it be otherwise that lexical and grammatical development track each other:  Just because the input contains information regarding the lexicon "at the same time" as information regarding grammar, doesn't mean that the mechanisms for learning (abstracting the relevant information) are the same and/or that they are stored/represented in a common system.  Input could simply be a "third party" explanation - lexical and grammatical development track each other because both are dependent on input that varies across individuals, and some individuals provide more input that feeds both systems, and other individuals provide less input.  What is extracted, how, and by what systems could be completely independent.   Hoff has recently made this argument using bilinguals: "We propose that a common influence of properties of input on vocabulary and grammatical development is the source of their correlated but uncoupled growth. " Hoff, E., Quinn, J. M., & Giguere, D. (2017). What explains the correlation between growth in vocabulary and grammar? New evidence from latent change score analyses of simultaneous bilingual development. Developmental Science, (March 2016), 1–16. http://doi.org/10.1111/desc.12536
