### ISSUE TITLE
birth order for french WS

### ISSUE THREAD

**Issue by mcfrank** [langcog/wordbank-book#61]
check data import, right now all kids are firstborn according to Ch3

**Comment by mikabr** [comment]
The French data from Sophie Kern has a `birth_order_num` column, which is what's currently being imported for birth order, but that's clearly wrong because the only values in the column are 1 and blank. Not sure what this is actually supposed to be. There's another column `birth_order` that has values 0/1/2/3/4/5/10 -- this is probably the actual birth order, but is it zero-indexed???

**Comment by mikabr** [comment]
decision: 0 means unique (i.e. first), 1/2/3/4/5 mean that order, 10 is data entry error
